#!/bin/sh

mkdir -p /etc/docker

# alpine doesn't like the containerd-snapshotter and userland-proxy
# (this works for now)
cat > /etc/docker/daemon.json <<EOF
{
  "features": {
    "containerd-snapshotter": false
  },
  "userland-proxy": false
}
EOF


exec dockerd ${DOCKERD_OPTS}
